### ISSUE TITLE
Registered account, supplied API key, getForecast() returns null

### ISSUE THREAD

**Issue by ctrlaltdylan** [jaimz22/Overcast#2]
Tried string and casting to float for long and lat, but $forecast is always null.

**Comment by jaimz22** [comment]
Could you provide some of your code?

**Comment by vesper8** [comment]
I was having the same problem, testing in a Laravel 5.2 installation that comes with guzzle 6.1

I guess guzzle is the problem.. I was not specifying the client adapter so it was probably trying to use the new guzzle and failing. When I specified your FileGetContentsClientAdapter then the forecast was no longer null and your example was working properly

**Comment by jaimz22** [comment]
excellent! I'll see what's up with it and guzzle 6.1. thanks for the info

**Comment by leventekk** [comment]
i've got the same issue, but after installing guzzle 5.3.1, it works properly.

**Comment by jaimz22** [comment]
awesome, I'll have to take the time to fix this. it doesn't do anyone any good if it's tied to old versions.

@leventekk which version of guzzle were you using when you encountered this issue?

**Comment by leventekk** [comment]
@jaimz22 latest version (6.2.1). but i've tried all of the 6.x versions without a success.

**Comment by jaimz22** [comment]
I finally found time to take care of this! give this newest commit a shot.

**Comment by jaimz22** [comment]
I'm closing this as I assume it's fixed at this point.
