### ISSUE TITLE
Impossible to pass multiple parameters to the API

### ISSUE THREAD

**Issue by ajoah** [jaimz22/Overcast#7]
Hi :)

This code doesn't work : 
```
$overcast = new \VertigoLabs\Overcast\Overcast('YOUR API KEY');
$forecast = $overcast->getForecast(37.8267,-122.423,null, ['units' => 'si', lang='fr'])
```
It returns a null value.

Because of ClientAdapter::buildRequestParameters which is incorrect.
Example : 
Entry :
```
array (size=2)
  'units' => string 'si' (length=2)
  'lang' => string 'fr' (length=2)
```
output :
```
string 'units=silang=fr' (length=15)
```
Instead of 
```
string 'units=si&lang=fr' (length=16)
```

**Comment by jaimz22** [comment]
I can't recreate this issue. 

I should point out that `['units' => 'si', lang='fr']` isn't valid. 

Can you provide more information?

Here's an example of the exact `buildRequestParameters` method producing correct results:
http://sandbox.onlinephpfunctions.com/code/7565a7fcfd09185f0e5f04f4c4d2d4c273737d65

**Comment by ajoah** [comment]
Sorry it's my fault, the bug has been fixed (#6). But it has not been released so i installed the buggy version with composer.

You should make a new release :)

**Comment by jaimz22** [comment]
shoot, I must have missed that. That is something that I will fix!

**Comment by jaimz22** [comment]
A new release has been published

**Comment by ajoah** [comment]
Perfect, thank you 👍
